#prepared by Eng. Mohamed Mostafa (Learn in Depth)
CC=arm-none-eabi-
CFLAGS=-mcpu=arm926ej-s -g
INCS=-I .
LIBS=
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
As = $(wildcard *.s)
AsOBJ = $(As:.s=.o)
all: learn-in-depth.bin
	@echo "==============Build is Done==============="

%.o:%.s
	$(CC)as.exe $(CFLAGS) $< -o $@
%.o: %.c 
	$(CC)gcc.exe $(CFLAGS) $(INCS) -c  $< -o $@
learn-in-depth.elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=Map_File.map
learn-in-depth.bin: learn-in-depth.elf
	$(CC)objcopy.exe -O binary  $<  $@

clean_all:
	rm *.o *.elf *.bin
	@echo "==============Everything clean==============="

clean:
	rm  *.elf *.bin