#prepared by Eng. Mohamed Mostafa (Learn in Depth)
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m3 -mthumb -gdwarf-2
INCS=-I .
LIBS=
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
As = $(wildcard *.s)
AsOBJ = $(As:.s=.o)
Project_name=learn-in-depth-cortexM3
all: $(Project_name).bin
	@echo "==============Build is Done==============="

%.o:%.s
	$(CC)as.exe $(CFLAGS) $< -o $@
%.o: %.c 
	$(CC)gcc.exe $(CFLAGS) $(INCS) -c  $< -o $@ -std=c99
$(Project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=Map_File.map
$(Project_name).bin: $(Project_name).elf
	$(CC)objcopy.exe -O binary  $<  $@

clean_all:
	rm *.o *.elf *.bin
	@echo "==============Everything clean==============="

clean:
	rm  *.elf *.bin